### ISSUE TITLE
There is no need to create SSH key-pair per user

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/hpc-qaas#1]
@rutgervandeelen 

In the code referred below, you seem to check and create a SSH key pair per user.  This is to my understanding not necessary.

The entire QaaS can just use one key pair with the private key held by (and only accessible for) the QaaS service user; while the public key is distributed into users' ~/.ssh/authorized_keys file.  This already allows QaaS service user to SSH into individual user's account.

https://github.com/Donders-Institute/hpc-qaas/blob/9bb5d69688f42c2e565113340027bb9cdacca184/internal/server/handlers.go#L81

**Comment by aardkronkel** [comment]
You are correct. I have changed this in commit e2d52b39120736e56195a51eadc34b56d81b5837.
