### ISSUE TITLE
support POST, PUT and GET

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/hpc-qaas#11]
````
roboos@mentat005> wget https://qaas.dccn.nl:443/xxxx

--2019-03-16 10:20:00--  https://qaas.dccn.nl/xxxx
Resolving qaas.dccn.nl (qaas.dccn.nl)... 131.174.44.44
Connecting to qaas.dccn.nl (qaas.dccn.nl)|131.174.44.44|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-03-16 10:20:00 ERROR 404: Not Found.
````

**Comment by robertoostenveld** [comment]
I tracked it over `131.174.44.44` to `dccn-dk001.dccn.nl` and used localhost in the end, but still get the same error. So the problem is not in the gateway, but seems to be on the final server itself.

**Comment by robertoostenveld** [comment]
here the same, now with curl showing more details on what it returns

```
roboos@mentat005> curl https://qaas.dccn.nl:443/6cfb79d9-7c91-472f-aa01-1742634d69d7

<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
```

**Comment by robertoostenveld** [comment]
... and on the server itself

```
roboos@dccn-dk001> curl http://localhost:5111
404 page not found
```

**Comment by robertoostenveld** [comment]
sorry, the last one was wrong: I should have included the identifier.

I tried `http://localhost:5111/xxx` and `http://localhost:5111/webhook/xxx` with xxx the identifier. Neither works.

**Comment by robertoostenveld** [comment]
Ah, i found it. The server does not respond to GET requests.

```
roboos@dccn-dk001> curl -X POST http://localhost:5111/webhook/xxx
Webhook handled successfully
```

Using `wget` and `curl` for testing seem very logical, and hence have to be documented. 

Also external services that trigger the webhook might be using either POST, PUT and GET, so all three should be supported.

**Comment by hurngchunlee** [comment]
Since the tigger will provide payload, it is not normal for GET as it is in general not an action with http request body. It make sense to support PUT.

**Comment by hurngchunlee** [comment]
Btw, please stay interfacing only the host qaas.dccn.nl instead of logging in the internal server.

**Comment by hurngchunlee** [comment]
I did a bit search and saw that POST seems to be the only method that Webhook should support: https://web.archive.org/web/20120413121142/http://wiki.webhooks.org/w/page/13385124/FrontPage

> The concept of a WebHook is simple. A WebHook is an HTTP callback: an HTTP POST that occurs when something happens; a simple event-notification via HTTP POST.

Given that perspective, I don't expect any Webhook trigger will use anything rather than POST.

**Comment by robertoostenveld** [comment]
> Since the tigger will provide payload, it is not normal for GET as it is in general not an action with http request body. It make sense to support PUT.

Not all external triggers will provide a payload. E.g. with IFTTT it is optional, and the user can specify whether it should be one of 

<img width="444" alt="Screen Shot 2019-03-16 at 15 35 03" src="https://user-images.githubusercontent.com/899043/54476735-1d954600-4801-11e9-9e1e-64ad981d6ee7.png">

**Comment by hurngchunlee** [comment]
I think IFTTT is beyond webhook as I see there are also other methods such as DELETE, PATCH and OPTIONS.  What do those methods mean to the webhook?  or shall we implement something like [resthook](http://resthooks.org) to give all those methods a semantic meaning?

Within the scope of webhook, I don't think we need to support all those methods just because IFTTT allows user to set HTTP method.  Moreover, if POST is an option of IFTTT, one could just use it to call the webhook provided by the service (even there is no payload).

**Comment by robertoostenveld** [comment]
I do think that we should discuss what to support and what not. I don't think that the full IFTTT list makes sense, but it also does not make sense to only consider github as the client making requests.

**Comment by robertoostenveld** [comment]
regardless of what is supported: supported requests should be explicitly documented and unsupported requests should result in a meaningful error message.

**Comment by hurngchunlee** [comment]
> regardless of what is supported: supported requests should be explicitly documented and unsupported requests should result in a meaningful error message.

That I totally agree.

**Comment by hurngchunlee** [comment]
Just for the record.  When the method is not supported, the service should return "405 Method Not Allowed" instead of "404 Not Found".

**Comment by aardkronkel** [comment]
We need to discuss which use cases we want to support.

I agree: Clear documentation is key.

1. To trigger a qsub command it makes sense to use `POST`.  If we really want it we can allow `PUT` as well.
2. In the next release we will return a `405 Method Not Allowed` where appropriate (instead of `404 Not Found`). See commit c009dcc4c862c6db19967b7be96038a901334df4.

**Comment by aardkronkel** [comment]
I have just added an Intranet page at the DCCN. 
To find the page: search for example for keyword "webhook" or "hpc-webhook".

**Comment by robertoostenveld** [comment]
I added some documentation to the introduction on using `curl -X POST` for testing. The GET and PUT are not mentioned in the documentation, and not supported at the moment (afaik). Let's not implement them until someone (other than me) asks for it.
