### ISSUE TITLE
rename script.sh

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/hpc-qaas#12]
Since the `script.sh` file is not to be executed itself, I propose to call it `script`. That aligns better with `payload`, which ends up in the same directory.

**Comment by robertoostenveld** [comment]
or alternatively rename `payload` into `payload.json`

**Comment by aardkronkel** [comment]
Since `payload` can contain other things than JSON plain text, I propose for the next release:

* keep the name `payload` as it is
* change `script.sh` to `script`

**Comment by robertoostenveld** [comment]
this has been addressed
