### ISSUE TITLE
Missing webhook path in the returned Webhook URL

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/hpc-qaas#13]
@rutgervandeelen 

I just noticed that the URL returned from the `database.getRow` doesn't contain the `server.WebhookPath` (see the link below).   If one takes that URL and call it directly, the 404 NOT FOUND is returned.

https://github.com/Donders-Institute/hpc-qaas/blob/c9285264bbadb48536d1d95da4f30f18b256f123/internal/server/database.go#L135

**Comment by aardkronkel** [comment]
Indeed `/webhook` was missing in the URL. See commit 2be195dff27796382b2d738a660d57afd4f843b3.
