### ISSUE TITLE
rename .webhooks to .webhook

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/hpc-qaas#15]
for consistency it would be better if the directory would not have an "s" in its name.

**Comment by aardkronkel** [comment]
Ok, we will change it to `.webhook` then

**Comment by aardkronkel** [comment]
@hurngchunlee When you are back could you be so kind to recompile and install the hpcutil tools again? And then run the `docker-deploy.sh` script to restart the server? Thank you in advance.

**Comment by robertoostenveld** [comment]
has this happened by now? And if so, can I migrate my currently configured webhooks using 

    cd $HOME
    mv .webhooks .webhook

or is something more needed?

**Comment by aardkronkel** [comment]
I am sorry to inform you that it involves more. 
You need to configure the webhooks again.
(This will not be the case in future maintenance actions.)

1. Perform the following for each of your scripts:
`hpcutil webhook create example_script.sh`

2. Reconfigure the corresponding webhook clients

The new results can be found in `.webhook`.
The old results in `.webhooks` can be deleted or kept depending on what you want.

**Comment by robertoostenveld** [comment]
no worries, it was not a lot work either to reconfigure the two webhooks that I have running. 

It seems that this issue is full resolved, hence I will close it
