### ISSUE TITLE
webhook server database being cleaned when service restarted

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/hpc-qaas#17]

**Comment by hurngchunlee** [comment]
figured out that the postgresql database is not persistent in the container.

In the docker-compose.yml file, I don't see the volume for the postgresql database.

**Comment by robertoostenveld** [comment]
FYI, I just recreated my web hooks

roboos@mentat001> hpcutil webhook list

```
<empty>

roboos@mentat001> hpcutil webhook create ./fieldtrip.sh 
INFO[0000] webhook created successfully with URL: https://hpc-webhook.dccn.nl:443/webhook/91580b45-xxx

roboos@mentat001> hpcutil webhook create ./website.sh   
INFO[0000] webhook created successfully with URL: https://hpc-webhook.dccn.nl:443/webhook/22be267c-xxx 

roboos@mentat001> hpcutil webhook list

22be267c-xxx
	Description     : 
	Creation time   : 2019-07-31T07:53:49Z
	Script path     : /home/mrphys/roboos/.webhook/website.sh
	Webhook URL     : https://hpc-webhook.dccn.nl:443/webhook/22be267c-xxx

91580b45-xxx
	Description     : 
	Creation time   : 2019-07-31T07:53:42Z
	Script path     : /home/mrphys/roboos/.webhook/fieldtrip.sh
	Webhook URL     : https://hpc-webhook.dccn.nl:443/webhook/91580b45-xxx
```

**Comment by aardkronkel** [comment]
The database is now persisted in the docker-compose file on the server.

**Comment by hurngchunlee** [comment]
@rutgervandeelen in the environment file, you set PGDATA explicitly to non-default directory: https://github.com/Donders-Institute/hpc-webhook/blob/70e9e8a13c3eb1c8ea8823d28f35968f4981a62e/configs/hpc-webhook-database.env.example#L20

I don't think it is necessary; also due to the difference between this path and the path in docker-compose file for data persistence.  We didn't actually persistent the data at all since August last year ...

**Comment by aardkronkel** [comment]
It appears it was not properly tested by me.

I have removed the wrong `PGDATA=/data/postgres` causing the trouble and restored the registered hooks from a backup I made on 24 October 2019.
