### ISSUE TITLE
As a user, I would like the webhook server to handle trigger in asynchronous way

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/hpc-qaas#19]
so that triggers from GitHub (and maybe others) will not be terminated after exceeding the expected response time.

GitHub expects the webhook server to response within 10 seconds, otherwise it terminates the call.  See [this document from GitHub](https://developer.github.com/v3/guides/best-practices-for-integrators/#favor-asynchronous-work-over-synchronous).

When it happens, the NGINX proxy server reports the following error log:

```
access.hpc-webhook.log-20191019.gz:192.30.252.99 - - [18/Oct/2019:13:19:09 +0200] "POST /webhook/91580b45-03e0-4b6f-9001-2c76e7ac4e4a HTTP/1.1" 499 0 "-" "GitHub-Hookshot/3b07851"
access.hpc-webhook.log-20191019.gz:140.82.115.245 - - [18/Oct/2019:13:34:08 +0200] "POST /webhook/91580b45-03e0-4b6f-9001-2c76e7ac4e4a HTTP/1.1" 499 0 "-" "GitHub-Hookshot/3b07851"
access.hpc-webhook.log-20191019.gz:140.82.115.251 - - [18/Oct/2019:15:40:31 +0200] "POST /webhook/91580b45-03e0-4b6f-9001-2c76e7ac4e4a HTTP/1.1" 499 0 "-" "GitHub-Hookshot/3b07851"
access.hpc-webhook.log-20191019.gz:192.30.252.97 - - [18/Oct/2019:23:48:16 +0200] "POST /webhook/91580b45-03e0-4b6f-9001-2c76e7ac4e4a HTTP/1.1" 499 0 "-" "GitHub-Hookshot/6c1acbb"
access.hpc-webhook.log-20191020.gz:140.82.115.245 - - [19/Oct/2019:15:45:18 +0200] "POST /webhook/91580b45-03e0-4b6f-9001-2c76e7ac4e4a HTTP/1.1" 499 0 "-" "GitHub-Hookshot/6c1acbb"
access.hpc-webhook.log-20191020.gz:140.82.115.249 - - [19/Oct/2019:20:43:59 +0200] "POST /webhook/91580b45-03e0-4b6f-9001-2c76e7ac4e4a HTTP/1.1" 499 0 "-" "GitHub-Hookshot/6c1acbb"
access.hpc-webhook.log-20191020.gz:192.30.252.98 - - [19/Oct/2019:23:46:51 +0200] "POST /webhook/91580b45-03e0-4b6f-9001-2c76e7ac4e4a HTTP/1.1" 499 0 "-" "GitHub-Hookshot/6c1acbb"
```

**Comment by hurngchunlee** [comment]
@rutgervandeelen  My suggestion is to return success (i.e. HTTP CODE 200) when the payload is successfully written to the home directory of the corresponding webhook.  Leave the ssh and qsub parts executed in the background asynchronously using the go routine + channel.

**Comment by aardkronkel** [comment]
The hpc-webhook server now responds after the payload has been delivered. See commit 70e9e8a13c3eb1c8ea8823d28f35968f4981a62e and e840abdfcf1aca859d6ef1dc286589e684223279. The new version (tagged as 0.4.1) has been deployed.

**Comment by robertoostenveld** [comment]
thanks, my github web hooks are happy again!

![Screenshot 2019-10-25 at 10 31 21](https://user-images.githubusercontent.com/899043/67555961-9f900a80-f712-11e9-97e3-7c43b1839804.png)
