### ISSUE TITLE
Return ConfigurationResponse in the ConfigurationHandler rather than in the WebhookHandler

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/hpc-qaas#2]
@rutgervandeelen 

Please return the ConfigurationResponse after the new webhoook is registered.  This allows the client to give user a feedback with the Webhook URL he/she can then use to registry it on a Webhook trigger (e.g. on GitHub).

You seem to return the ConfigurationResponse in the WebhookHandler, which I don't think is necessary as I don't think the Webhook trigger (such as GitHub) will be able to process this response.

https://github.com/Donders-Institute/hpc-qaas/blob/9bb5d69688f42c2e565113340027bb9cdacca184/internal/server/handlers.go#L113

**Comment by aardkronkel** [comment]
Good catch. Now the ConfigurationResponse in is returned in the ConfigurationHandler instead of in the WebhookHandler. See commit eb40578123cc2d35d7a542b4121b93ae751a3371.
