### ISSUE TITLE
Database table recreated after restart of container? 

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/hpc-qaas#3]
@rutgervandeelen 

It looks to me that this will result in removing existing table after restart of the Postgresql container.  Is it intended?

https://github.com/Donders-Institute/hpc-qaas/blob/612d7ee18355cc1d12e149b9d6306ec048fa0c55/init/01-initialize-database.sh#L5

**Comment by aardkronkel** [comment]
Good catch. This was intendend for testing. I have replaced it with CREATE TABLE IF NOT EXIST qaas ...  See commit  47ec527a536fdc161f269e9b09721f5d87d845d2. I have also updated the script on the Docker server.
