### ISSUE TITLE
Add REST endpoint for deleting webhook

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/hpc-qaas#4]
The HTTP method should be DELETE and the URL should be:

http(s)://{QaasHost}:{QaasPort}/configuration/{WebhookID}

It should just return HTTP code 200 on success, 404 if the {WebhookID} is not found.

Question: how to be sure the webhook is deleted by the owner of it, not any random user?

**Comment by aardkronkel** [comment]
At the moment we lean on both the end point for the DELETE HTTP request 

`http(s)://{QaasHost}:{QaasPort}/configuration/{WebhookID}` 

and the JSON body which contains the (hash, groupname, username), for example 

`{"hash": "550e8400-e29b-41d4-a716-446655440001", "groupname": "groupname", "username": "username", "description": ""}`

**Comment by aardkronkel** [comment]
We could introduce a DELETE HTTP request to delete ALL webhooks for a certain (groupname, username) with end point

http(s)://{QaasHost}:{QaasPort}/configuration

and a JSON body which contains the (groupname, username), for example

{"hash": "", "groupname": "groupname", "username": "username", "description": ""}

**Comment by aardkronkel** [comment]
Delete functionality does not work.

The qaas server logs show `invalid JSON body`.

It appears that the qaas server recieves a body that is empty from the qaas client.

**Comment by hurngchunlee** [comment]
But the client does sent request body.  Using the `-v` option of the client, you see the request data being sent.

```
DEBU[0000] request data: {"hash":"e3e5e1c2-f7d8-47fa-b989-607488d66472","groupname":"tg","username":"honlee","description":""} 
ERRO[0000] fail to delete webhook e3e5e1c2-f7d8-47fa-b989-607488d66472: 404 Not Found (HTTP CODE: 404) 
```

**Comment by hurngchunlee** [comment]
sorry. accidentally closed it.  Reopen it now.

**Comment by hurngchunlee** [comment]
I think the `invalid JSON body` is misleading due to the fact that the client firstly make a GET call to determine whether the webhook exists in the QaaS database.  I have removed this check, but then I saw the following error in the qaas server's log:

```
qaas_server.1.442sd223l9up@dccn-dk005.dccn.nl    | &{src:0xc000238ea0 hdr:<nil> r:<nil> closing:true doEarlyClose:true mu:{state:0 sema:0} sawEOF:false closed:false earlyClose:false onHitEOF:0x662570}
qaas_server.1.442sd223l9up@dccn-dk005.dccn.nl    | pq: syntax error at or near "("
```
Looks like a SQL syntax error??

**Comment by aardkronkel** [comment]
Fixed it. Was indeed a bug in the DELETE SQL statement.

Deleting a webhook now works. See commit 7c1510eb010636e5dc327069ca40c8657e1ad685. Also made a new release (v0.2.1) for demoing.

Note: When an attempt is made to delete a webhook with an incorrect (groupname, username) the webhook is not deleted in the database, which is what we want. However, the user is not notified in this case. An error should be reported.

**Comment by hurngchunlee** [comment]
This can also leave to the client to firstly "get" webhook from the server to check if the webhook to be deleted actually exists and belongs to the user/group before making the "delete" call. See the new issue #8.

**Comment by hurngchunlee** [comment]
The existence check before deletion is performed in the client code. 

@rutgervandeelen  This issue may be closed if the server ensures that the webhook information cannot be retrieved by a user that is not the same as the webhook creator.

**Comment by aardkronkel** [comment]
We have tested the following:
1. Create a webhook with a certain webhook id as user A
2. Attempt to delete the webhook with the same webhook id as user B
The attempts were not succcessful as expected: 
other users than the webhook creator cannot delete the webhook.
