### ISSUE TITLE
Add REST endpoint for getting detail about a webhook

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/hpc-qaas#5]
The HTTP method should be GET, and the URL should be

http(s)://{QaasHost}:{QaasPort}/configuration/{webhookId}

**Comment by aardkronkel** [comment]
At the moment we lean on both the end point for the GET HTTP request 

`http(s)://{QaasHost}:{QaasPort}/configuration/{WebhookID}` 

and the JSON body which contain the (hash, groupname, username), for example 

`{"hash": "550e8400-e29b-41d4-a716-446655440001", "groupname": "groupname", "username": "username", "description": ""}`

to obtain info about a SINGLE webhook.

**Comment by aardkronkel** [comment]
Note: the GET HTTP request 

`http(s)://{QaasHost}:{QaasPort}/configuration` 

and the JSON body which contain the (groupname, username), for example 

`{"hash": "", "groupname": "groupname", "username": "username", "description": ""}`

is used to obtain the LIST of webhook info for this  (groupname, username).
