### ISSUE TITLE
Return the webhook URL as part of the Webhook info

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/hpc-qaas#7]
@rutgervandeelen 

It's nice to see that you return whatever in the database Item back as the information; but I miss the full Webhook URL which needs to be constructed by taking the Hash of the Webhook and the base URL of the webhook trigger.  Please also provide it as part of the returned Webhook info.  

https://github.com/Donders-Institute/hpc-qaas/blob/96650f36c11ec6adb4aa0f1faa50e15a344ec6c7/internal/server/configuration.go#L28

**Comment by aardkronkel** [comment]
Done. See for example code in after commit b6f5f4fedbe273c5bd81a8f80e5b32d2134555c0.

**Comment by hurngchunlee** [comment]
Shouldn’t the returned URL with port 443?

**Comment by aardkronkel** [comment]
My mistake. Just fixed the ports in commit 630a60f66e0a29a10b04fcc3d0b9363bd334fd4a.

**Comment by hurngchunlee** [comment]
Shall we close this one?  The Webhook URL is already available.
