### ISSUE TITLE
Getting webhoook information from database should also match username (and/or group name)

### ISSUE THREAD

**Issue by hurngchunlee** [Donders-Institute/hpc-qaas#8]
@rutgervandeelen 

I think it is safer to also match the username (and/or group name) when retrieving webhook information from the database. 

https://github.com/Donders-Institute/hpc-qaas/blob/7c1510eb010636e5dc327069ca40c8657e1ad685/internal/server/database.go#L96

**Comment by aardkronkel** [comment]
Good point. Changed `getRow` accordingly in commit 32fc7069cf76c1baffa43de58f3489e3a2400165.
